### ISSUE TITLE
Heroku Login

### ISSUE THREAD

**Issue by thoughtfuldata** [docker/login-action#251]
I have login to Heroku Registry, which works fine
After docker/build-push-action( works fine), but I need to to run ```heroku container:release web``` to get the app deployed on Heroku. since docker/build-push-action doesn't run this command,  I have tried:" 
``` 
      - name: publish
        run: |
        heroku container:release web -a app_name
```

however I get this error: 
```
 ▸    Invalid credentials provided.
heroku: Press any key to open up the browser to login or q to exit:  ▸    Invalid credentials provided.
Enter your Heroku credentials:
Email: 
```

How can I get this extra command to work with the credentials from login-action? or am I missing something?

**Comment by crazy-max** [comment]
Looking [at the docs](https://devcenter.heroku.com/articles/container-registry-and-runtime#logging-in-to-the-registry), `heroku container:login` is used to login to Heroku Registry. It seems to use the same protocol as `docker login` to be able to push an image on `registry.heroku.com` so that's why you are able to push your image with the action.

But to [release an image](https://devcenter.heroku.com/articles/container-registry-and-runtime#releasing-an-image) with `heroku container:release` you need to use `heroku login` command as stipulated in [their docs](https://devcenter.heroku.com/articles/container-registry-and-runtime#getting-started) too:

> and that you’re logged in to Heroku (`heroku login`).
