### ISSUE TITLE
(Question): lifecycle?

### ISSUE THREAD

**Issue by gotchipete** [docker/login-action#345]
Hey there!  Question about the usage/lifecycle of this action.. 

Our actions have multiple jobs, sometimes running in parallel via `matrix` - my question is, if I use this login job once in my action (say it's named `login`), and make the other jobs dependent on it (e.g. with `needs: login`) - will the other jobs' image pulls also be authenticated (assuming I set the `logout` property to `false`), or do I need to use this login action in each individual job in the action?

Thanks!

**Comment by crazy-max** [comment]
Each job runs on its own runner so you have to set the login action in each of them. More info: https://docs.github.com/en/actions/using-workflows/about-workflows#workflow-basics

**Comment by jgarplind** [comment]
Sorry to resurrect a closed issue, but I'm just curious to know - if this is not the use for the `logout` parameter, then how is it supposed to be used?

I assumed that the session would persist across jobs since that seemed to be the relevant use case.

Perhaps this could be clarified in the documentation?

Happy to provide a PR if you agree.
