### ISSUE TITLE
Issue: Login to public ECR action

### ISSUE THREAD

**Issue by bhautikpip** [docker/login-action#38]
I am receiving `Error response from daemon: Get https://public.ecr.aws/v2/: denied: Not Authorized` while using Login to ECR action in my workflow. I am able to run `aws ecr-public get-login-password --region us-east-1 | docker login -u AWS --password-stdin public.ecr.aws` in my local machine. Would you be able to confirm if it's a bug? I could not find ecr publish test in this repo so not sure if login to ecr actions has any issues or not.

Workflow error: https://github.com/bhautikpip/aws-xray-daemon/runs/1554928752?check_suite_focus=true
Workflow code: https://github.com/bhautikpip/aws-xray-daemon/blob/daemon-ecr-publish/.github/workflows/continuous-build.yml

**Comment by crazy-max** [comment]
@bhautikpip #37 has been merged to add support for Public ECR but no release have been created yet for this action because GitHub Runners does not currently support `ecr-public` command. (AWS CLI 2.1.4 on `ubuntu-20.04` and AWS CLI 1.18.185 on `ubuntu-latest`). See https://github.com/actions/virtual-environments/issues/2219#issuecomment-743021467

**Comment by crazy-max** [comment]
@bhautikpip AWS CLI is [has been updated](https://github.com/actions/virtual-environments/issues/2219#issuecomment-747215783) on GitHub Runners. Let me know if everything is ok.
